Context aware policies can be written with Rego
kubewarden/docs pull request #289
Opened 2023-10-26 08:51 UTC by flavio

Update the documentation to reflect the possibility to write context aware policies using Rego.

This is part of https://github.com/kubewarden/kubewarden-controller/issues/513

**Note for reviewers:** when looking at the preview site, make sure you switch to the "next" version of the documentation. Otherwise you will not see these changes :wink:

2023-10-26 08:55 UTC, flavio commented
There's some broken css when rendering tabs, see: https://deploy-preview-289--silly-bunny-8cedd0.netlify.app/next/writing-policies/spec/context-aware-policies#rego-policies

I think it would be easier to just drop the tabs and move to dedicated sections:

```md
## Language SDK

### Rust
blah

### Go
blah

## Rego

### Gatekeeper
blah

### OPA

blah
```

What do you think?

2023-10-26 09:04 UTC, viccuad commented
I'm ok with dropping the tab. Also, I tend to search and navigate by doing `ctrl+F`, and tabs obscure content.

2023-10-26 09:05 UTC, viccuad approved these changes

2023-10-26 09:33 UTC, jhkrug commented
> I'm ok with dropping the tab. Also, I tend to search and navigate by doing `ctrl+F`, and tabs obscure content.

Ditto

2023-10-26 09:39 UTC, jhkrug requested changes
Some minor suggestions.

2023-10-26 09:39 UTC, jhkrug commented on docs/explanations/context-aware-policies.md
> +More detailed information about context aware policies can be found inside of [this section](../writing-policies/spec/05-context-aware-policies.mdx)
```suggestion
More detailed information about context aware policies can be found in [this section](../writing-policies/spec/05-context-aware-policies.mdx)
```

2023-10-26 09:39 UTC, jhkrug commented on docs/writing-policies/rego/01-intro-rego.md
> +Rego policies support context aware data stating from the Kubewarden 1.9 release.
```suggestion
Rego policies support context aware data starting from the Kubewarden 1.9 release.
```

2023-10-26 09:39 UTC, jhkrug commented on docs/writing-policies/rego/01-intro-rego.md
>  The Rego language is a tailor made language designed to embrace
```suggestion
The Rego language is a domain specific language designed to embrace
```

2023-10-26 09:39 UTC, jhkrug commented on docs/writing-policies/spec/05-context-aware-policies.mdx
>  The policy server performs caching of the results obtained from the Kubernetes API server to reduce the amount of load of this core piece of Kubernetes.
```suggestion
The policy server performs caching of the results obtained from the Kubernetes API server to reduce the amount of load on this core part of Kubernetes.
```

2023-10-26 12:42 UTC, flavio commented
I've removed the tabgroup. There's a DCO failure right now, I'll fix it before merging the PR

2023-10-26 13:24 UTC, jhkrug approved these changes
lgtm

Also, I'll be going through these again in a while as part of my review tasks.

2023-10-27 06:05 UTC, fabriziosestito approved these changes

2023-10-27 15:11 UTC, merged