refresh 05 writing a rust mutating policy
kubewarden/docs pull request #299
Opened 2023-10-27 13:02 UTC by jhkrug

2023-10-30 12:28 UTC, jvanz requested changes
Besides the little typo, LGTM

2023-10-30 12:28 UTC, jvanz commented on docs/writing-policies/rust/05-mutation-policy.md
> +You need to chnage the function to approve the request via the
```suggestion
You need to change the function to approve the request via the
```

2023-10-30 12:29 UTC, jhkrug commented on docs/writing-policies/rust/05-mutation-policy.md
> +You need to chnage the function to approve the request via the
Thank you.

2023-10-31 15:16 UTC, viccuad approved these changes
LGTM!

2023-11-24 15:53 UTC, closed without merging

2023-11-24 15:54 UTC, jhkrug commented
Closing as #295 ended up having all the changes.