Using ServiceMonitors directly
kubewarden/docs pull request #312
Opened 2023-11-17 12:30 UTC by dgiebert

## Description

Changes [Metrics Quickstart](https://docs.kubewarden.io/operator-manual/telemetry/metrics/quickstart) to use ServiceMonitors instead of modifying the Prometheus Chart

## Additional Information

### Tradeoff

The Kubewarden UI needs to be adapted to search for ServiceMonitors and not the Chart

2023-11-17 13:09 UTC, dgiebert commented on versioned_docs/version-1.9/operator-manual/telemetry/metrics/01-quickstart.md
> +Prometheus community Helm chart, but you can also use the Rancher Monitoring Chart.
Oh! Yes I will remove it.

2023-11-17 13:09 UTC, dgiebert commented
I clicked edit on the main page, but now really checking the source shouldn't this go in the unversioned section of the docs?

2023-11-17 13:54 UTC, jordojordo commented
Could you also remove the references to the Prometheus spec within the UI docs? https://docs.kubewarden.io/operator-manual/ui-extension/metrics#1-within-the-cluster-explorer-click-on-cluster-tools-in-the-side-navigation

2023-11-17 13:56 UTC, viccuad requested changes
> I clicked edit on the main page, but now really checking the source shouldn't this go in the unversioned section of the docs?

Argh, yes, you are right, sorry. This should go into the `docs/` folder.

2023-11-17 14:11 UTC, dgiebert commented
> Could you also remove the references to the Prometheus spec within the UI docs? https://docs.kubewarden.io/operator-manual/ui-extension/metrics#1-within-the-cluster-explorer-click-on-cluster-tools-in-the-side-navigation

Can do, but shouldn't there be a pointer to the Install Section for Prometheus/Opentelemetry?

2023-11-17 14:56 UTC, jordojordo commented
> shouldn't there be a pointer to the Install Section for Prometheus/Opentelemetry?
Yes you're right, there should be at least a pointer to the section.

2023-11-17 15:06 UTC, dgiebert commented
@jordojordo adapted the UI section of the documentation as well

2023-11-17 15:16 UTC, jordojordo approved these changes
LGTM

2023-11-20 08:07 UTC, kravciak requested changes
namespaceSelectors in UI doc point to `kubewarden`, but we use `cattle-kubewarden-system` in Rancher

2023-11-20 08:23 UTC, kravciak requested changes

2023-11-20 08:25 UTC, kravciak commented
> > namespaceSelectors point to `kubewarden`, but we use `cattle-kubewarden-system` in Rancher
> 
> I can change that, but all docs use the `kubewarden` namespace (e.g. [here](https://docs.kubewarden.io/operator-manual/telemetry/metrics/quickstart#install-kubewarden))

Section of [doc about UI extension](https://docs.kubewarden.io/operator-manual/ui-extension/install) use cattle-kubewarden-system ns. Kubewarden namespace does not exist if you install through extension.

2023-11-20 08:30 UTC, viccuad commented on docs/operator-manual/ui-extension/metrics.md
> +      - kubewarden
```suggestion
      - cattle-kubewarden-system
```

2023-11-20 08:30 UTC, viccuad commented on docs/operator-manual/ui-extension/metrics.md
> +      - kubewarden
```suggestion
      - cattle-kubewarden-system
```

2023-11-20 08:33 UTC, dgiebert commented
Ok, will fix and implement the changes this evening

2023-11-20 08:39 UTC, kravciak commented on docs/operator-manual/ui-extension/metrics.md
> +  namespace: kubewarden
```suggestion
  namespace: cattle-kubewarden-system
```

2023-11-20 08:39 UTC, kravciak commented on docs/operator-manual/ui-extension/metrics.md
> +  namespace: kubewarden
```suggestion
  namespace: cattle-kubewarden-system
```

2023-11-20 15:10 UTC, dgiebert commented
Done, also checked with `grep -r 'namespace: kubewarden'` there is no other mention in the docs :+1:

2023-11-21 08:23 UTC, viccuad commented on docs/operator-manual/telemetry/metrics/01-quickstart.md
> +In our case, we are adding a Service monitor targeting the `kubewarden` namespace for services that
```suggestion
In our case, we are adding a ServiceMonitor targeting the `kubewarden` namespace for services that
```

2023-11-21 08:29 UTC, dgiebert commented on docs/operator-manual/ui-extension/metrics.md
> +The Prometheus Operator is required.
Could change this to say "A Prometheus Operator is required" that would also include the Rancher one as an option?

2023-11-21 08:32 UTC, viccuad commented on docs/operator-manual/telemetry/metrics/01-quickstart.md
> +  namespace: cattle-kubewarden-system
```suggestion
  namespace: kubewarden
```

2023-11-21 08:32 UTC, viccuad commented on docs/operator-manual/ui-extension/metrics.md
> +      - kubewarden
```suggestion
      - cattle-kubewarden-system
```

2023-11-21 08:32 UTC, viccuad commented on docs/operator-manual/ui-extension/metrics.md
> +      - kubewarden
```suggestion
      - cattle-kubewarden-system
```

2023-11-21 08:34 UTC, dgiebert commented on docs/operator-manual/telemetry/metrics/01-quickstart.md
> +  namespace: cattle-kubewarden-system
Don't we install everything then to `cattle-kubewarden-system`?

2023-11-21 08:40 UTC, viccuad approved these changes
Many thanks and sorry for the confusion!

2023-11-21 08:41 UTC, kravciak approved these changes

2023-11-21 08:41 UTC, merged

2023-11-21 08:43 UTC, kravciak commented
Thanks for the contribution!