Add mutating policies danger explanations
kubewarden/docs pull request #336
Opened 2024-01-19 11:26 UTC by viccuad

## Description

Fix https://github.com/kubewarden/docs/issues/335.

## Test

## Additional Information

### Tradeoff

### Potential improvement

2024-01-19 11:26 UTC, viccuad commented on docs/tasksDir/mutating-policies.md
> +infinite feedback loop of mutations.
Maybe it's worth to add a specific example of a bad `spec.rules` in this case?

2024-01-19 14:50 UTC, jhkrug approved these changes
lgtm

2024-01-19 16:24 UTC, flavio requested changes

2024-01-19 16:24 UTC, flavio commented on docs/tasksDir/mutating-policies.md
> +   this is happening.
This should be dropped. That applies to validating policies, not to mutating ones.

2024-01-19 16:24 UTC, flavio commented on docs/tasksDir/mutating-policies.md
> +   resource (be it native to Kubernetes, or a CRD).
This applies to validating policies, not to mutating ones.

We could say that targeting the higher level resource could however lead to loops if a controller is managing them. That includes for example controllers of GitOps solutions (like fleet, flux, argo, ...) or other 3rd party controllers that translate their own CRDs into Deployment objects.

2024-01-22 12:04 UTC, viccuad commented
@flavio tackled the suggestions, please re-review.

2024-01-22 14:00 UTC, jhkrug approved these changes
lgtm

2024-01-22 17:21 UTC, jvanz approved these changes

2024-01-24 09:11 UTC, merged