Update context aware documentation
kubewarden/docs pull request #355
Opened 2024-02-15 16:02 UTC by flavio

Cover a change introduced by the next release of Kubewarden.

This is related with https://github.com/kubewarden/kubewarden-controller/issues/575

2024-02-15 17:12 UTC, jhkrug requested changes
lgtm. one tiny typo.

2024-02-15 17:12 UTC, jhkrug commented on docs/reference/spec/05-context-aware-policies.md
> +and introduces more latency when evaluating an admission request.
```suggestion
The policy author can also decide to make a direct query, one that skips the cache entirely. In this way, fresh data is always
served. This however can cause more load on the Kubernetes API server (depending on how frequently the policy is triggered)
and introduces more latency when evaluating an admission request.
```

2024-02-15 17:15 UTC, flavio commented
@jhkrug thanks for the fix. I've merged it

2024-02-16 15:05 UTC, viccuad approved these changes
LGTM!

2024-02-19 09:13 UTC, merged