Add CEL intro and reusing VAP page
kubewarden/docs pull request #410
Opened 2024-06-12 12:56 UTC by viccuad

## Description

Part of https://github.com/kubewarden/cel-policy/issues/8.

## Test

## Additional Information

### Tradeoff

### Potential improvement

2024-06-13 14:13 UTC, flavio requested changes
LGTM, I left some minor suggestions

2024-06-13 14:13 UTC, flavio commented on docs/tutorials/writing-policies/CEL/01-intro-cel.md
> +apiextensions-apiserver.
```suggestion
`apiextensions-apiserver`.
```

2024-06-13 14:13 UTC, flavio commented on docs/tutorials/writing-policies/CEL/01-intro-cel.md
> +Kubewarden's [context-aware capabilities as native
```suggestion
Kubewarden's [host capabilities as native
```

2024-06-14 07:49 UTC, fabriziosestito approved these changes

2024-06-14 10:27 UTC, flavio approved these changes

2024-06-14 10:48 UTC, merged