feat: global toleration and affinity documentation.
kubewarden/docs pull request #426
Opened 2024-07-15 15:18 UTC by jvanz

## Description

Adds a new HowTo documentation explaining how users can define tolerations and affinity configuration for the whole Kubewarden stack.

2024-07-15 15:29 UTC, jhkrug requested changes
Hi, some minor suggestions if you like them.

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +# Configuring Tolerations and Affinity/Anti-Affinity for the Kubewarden Stack
```suggestion
# Configuring Tolerations and Affinity/Anti-Affinity for the Kubewarden stack
```

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +cronjob, and the PolicyServer custom resource.
```suggestion
Kubewarden provides features for reliability and correct
scheduling of its components in a Kubernetes cluster. 

Starting from version
1.15 of the Kubewarden Helm charts, two new fields, `tolerations` and
`affinity`, are introduced under the `global` value. These fields allow
users to define Kubernetes tolerations and affinity/anti-affinity settings for
the Kubewarden stack, including the controller deployment, audit scanner
cronjob, and the PolicyServer custom resource.
```

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +deployment, audit scanner cronjob, and the PolicyServer custom resource.
```suggestion
In this example, the tolerations defined are applied to the controller
deployment, audit scanner cronjob, and the PolicyServer custom resource.
```

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +are crucial for ensuring high availability, fault tolerance, and optimized
```suggestion
are useful for ensuring high availability, fault tolerance, and optimized
```

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +resource usage within the cluster.
```suggestion
resource usage in a cluster.
```

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +simplifies the configuration process by providing a single, unified approach to
```suggestion
simplifies the configuration process by providing a single approach to
```

2024-07-15 15:29 UTC, jhkrug commented on docs/howtos/production-deployments.md
> +By leveraging the `tolerations` and `affinity` fields, operators can fine-tune
```suggestion
By using the `tolerations` and `affinity` fields, operators can fine-tune
```

2024-07-16 06:22 UTC, flavio reviewed
Looks good to me, thanks for the update. I left one minor suggestion

2024-07-16 06:22 UTC, flavio commented on docs/howtos/production-deployments.md
> +chart has been deprecated and removed. Users should now use the
Something cannot be deprecated and removed at the same time. AFAIK we went straight to remove it

```suggestion
:::warning The old `affinity` configuration in the `kubewarden-default` Helm
chart has been removed. Users should now use the
```

2024-07-16 11:26 UTC, viccuad approved these changes
LGTM modulo Flavio's suggestions.

2024-07-16 13:04 UTC, merged