Clarify the sources usage on PolicyServer CRs
kubewarden/docs pull request #435
Opened 2024-08-07 14:59 UTC by viccuad

## Description

## Test

## Additional Information

### Tradeoff

### Potential improvement

2024-08-07 15:42 UTC, jhkrug requested changes
Some very minor suggestions.

2024-08-07 15:42 UTC, jhkrug commented on docs/reference/sources_yaml.md
> +using the `sources.yaml` file, configured via the `--sources-path` argument which specifies the file.
Very minor suggestion.

```suggestion
You can tune the push-pull behavior of `kwctl` and `policy-server` binaries with the `--sources-path` argument, 
for specifying the path to the `sources.yaml` file.
```

2024-08-07 15:42 UTC, jhkrug commented on docs/reference/sources_yaml.md
> +of this fields corresponds with their sections below.
Again, a very minor suggestion.

```suggestion
of these fields corresponds with the respective sections below.
```

2024-08-08 06:02 UTC, flavio commented
Thanks for the improvements to both of you!

2024-08-08 06:02 UTC, merged