feat: warning about the identity in the cosign verify.
kubewarden/docs pull request #461
Opened 2024-10-11 12:42 UTC by jvanz

## Description

Updates the tutorial of how to verify the signatures of the Kubewarden components adding a warning explaining how to have a more secure check by using the full URL in the subject/identity field.

Related to https://github.com/kubewarden/kubewarden-controller/issues/856

2024-10-11 14:19 UTC, viccuad approved these changes

2024-10-11 14:32 UTC, jvanz commented
@viccuad I've updated the PR to instructions on how to use the attestation files. Do you think that is enough?

2024-10-14 10:21 UTC, jhkrug requested changes
A small suggestion.

2024-10-14 10:21 UTC, jhkrug commented on docs/tutorials/verifying-kubewarden.md
> +We use Docker to build the images and their attestations. Therefore, the cosign
Would this read better?
```suggestion
We use Docker to build the images and their attestations. However, the cosign
```

2024-10-18 12:20 UTC, viccuad approved these changes

2024-10-18 13:45 UTC, merged