Some language improvements and better active voice for OTEL collector.
kubewarden/docs pull request #482
Opened 2024-12-23 13:12 UTC by jhkrug

As per title.

2024-12-24 16:36 UTC, jvanz requested changes
Thanks for the enhancements! I've only fixed some date to reflect the actual time when that piece of text has been written. Maybe we should create a tech-debt to double check that sentences or update them with more recent information.

2024-12-24 16:36 UTC, jvanz commented on docs/howtos/telemetry/10-opentelemetry-qs.md
> +At time of writing (2024-12-23) the latest cert-manager chart version is `v1.15.1`
```suggestion
At time of writing (2024-07-17) the latest cert-manager chart version is `v1.15.1`
```

2024-12-24 16:36 UTC, jvanz commented on docs/howtos/telemetry/10-opentelemetry-qs.md
> +At the time of writing (2024-12-23), only specific versions of OpenTelemetry are compatible
```suggestion
At the time of writing (2022-06-21), only specific versions of OpenTelemetry are compatible
```

2024-12-24 16:36 UTC, jvanz commented on docs/howtos/telemetry/20-tracing-qs.md
> +At the time of writing (2024-12-23), only specific versions of Jaeger are compatible with
```suggestion
At the time of writing (2022-06-21), only specific versions of Jaeger are compatible with
```

2024-12-24 16:36 UTC, jvanz commented on docs/howtos/telemetry/30-metrics-qs.md
> +At time of writing (2024-12-23) the latest chart version is `51.5.3`
```suggestion
At time of writing (2023-11-17) the latest chart version is `51.5.3`
```

2024-12-27 14:08 UTC, merged

2025-01-03 11:10 UTC, jhkrug commented
Nope, all good. Thanks.